---
- name: Get secrets
  import_tasks: secrets.yml

- name: Install GitLab Runner (Debian)
  become: yes
  import_tasks: install-debian.yml
  when: ansible_os_family == 'Debian'

- name: Install GitLab Runner (RedHat)
  import_tasks: install-redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Set global options
  become: yes
  import_tasks: global-setup.yml

- name: Register GitLab Runner
  import_tasks: register-runner.yml
  when: gitlab_runner_registration_token != ''

- name: Update4 gitlab-runner user
  become: yes
  import_tasks: user.yml
  when: gitlab_runner_registration_token != ''
