- name: get gitlab runner secrets
  shell: "aws secretsmanager get-secret-value --output text --profile {{ aws_profile|default('default') }} --query 'SecretString' --secret-id {{ gitlab_runner_secret_id }} | jq '.'"
  register: gitlab_runner_secrets

- debug:
  msg: "{{ gitlab_runner_secrets }}"
