- name: Get gitlab runner secrets
  delegate_to: 127.0.0.1
  shell: "aws secretsmanager get-secret-value --output text --profile {{ aws_profile|default('default') }} --query SecretString --secret-id {{ gitlab_runner_secret_id }} | jq '.'"
  register: gitlab_runner_secrets
