---
- name: Update gitlab-runner user
  user:
    name: "gitlab-runner"
    groups: [ "docker" ]
    uid: 1001

- name: Adding user's .ssh directory
  file:
    path: "/home/gitlab-runner/.ssh"
    owner: "gitlab-runner"
    group: "gitlab-runner"
    state: directory
    mode: "0700"

- name: Adding user's private key
  template:
    src: id_rsa.j2
    dest: "/home/gitlab-runner/.ssh/id_rsa"
    owner: "gitlab-runner"
    group: "gitlab-runner"
    mode: "0600"
  when: gitlab_runner_private_key_secret_id
